language: node_js
node_js:
  - "6"
  - "7"
  
dist: trusty
sudo: required
notifications:
  email: false
deploy:
  app: event-portal-frontend
  #provider: heroku
  #api_key:
  #  secure: *key*
  on:
    tags: true  
skip_cleanup: true
branches:
  only:
    - master

before_install:
  - npm i touch@latest
