language: node_js
node_js:
  - "6"
  - "7"
  
dist: trusty
sudo: required
notifications:
  email: false
deploy:
  app: event-portal-frontend
  #provider: heroku
  #api_key:
  #  secure: *key*
  on:
    tags: true  
skip_cleanup: true
branches:
  only:
    - master
apt:
 sources:
 — google-chrome
 packages:
 — google-chrome-stable
 — google-chrome-beta
 
before_install:
 — export CHROME_BIN=chromium-browser
 — export DISPLAY=:99.0
 — sh -e /etc/init.d/xvfb start
